//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.34003
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMZDM_Notifier.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool StartupWithSystem {
            get {
                return ((bool)(this["StartupWithSystem"]));
            }
            set {
                this["StartupWithSystem"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool MinimizeWhenClose {
            get {
                return ((bool)(this["MinimizeWhenClose"]));
            }
            set {
                this["MinimizeWhenClose"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool SilentMode {
            get {
                return ((bool)(this["SilentMode"]));
            }
            set {
                this["SilentMode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5")]
        public int NotifyStayTime {
            get {
                return ((int)(this["NotifyStayTime"]));
            }
            set {
                this["NotifyStayTime"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("200")]
        public int KeepMessageAmount {
            get {
                return ((int)(this["KeepMessageAmount"]));
            }
            set {
                this["KeepMessageAmount"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("全部")]
        public string LocationToShow {
            get {
                return ((string)(this["LocationToShow"]));
            }
            set {
                this["LocationToShow"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("30")]
        public int RefreshInterval {
            get {
                return ((int)(this["RefreshInterval"]));
            }
            set {
                this["RefreshInterval"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("400")]
        public int NotifyBoxWidth {
            get {
                return ((int)(this["NotifyBoxWidth"]));
            }
            set {
                this["NotifyBoxWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("300")]
        public int NotifyBoxHeight {
            get {
                return ((int)(this["NotifyBoxHeight"]));
            }
            set {
                this["NotifyBoxHeight"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool MinimizeWhenStartup {
            get {
                return ((bool)(this["MinimizeWhenStartup"]));
            }
            set {
                this["MinimizeWhenStartup"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool AutoStartFetching {
            get {
                return ((bool)(this["AutoStartFetching"]));
            }
            set {
                this["AutoStartFetching"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("优惠精选|http://feed.smzdm.com|True;海淘专区|http://haitao.smzdm.com/feed|True;经验盒子|http:" +
            "//jy.smzdm.com/feed|True;晒物广场|http://show.smzdm.com/feed|True;发现频道|http://fx.smz" +
            "dm.com/feed|True")]
        public string ChannelUrls {
            get {
                return ((string)(this["ChannelUrls"]));
            }
            set {
                this["ChannelUrls"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Setting {
            get {
                return ((string)(this["Setting"]));
            }
            set {
                this["Setting"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("data.xml")]
        public string DATA_FILENAME {
            get {
                return ((string)(this["DATA_FILENAME"]));
            }
            set {
                this["DATA_FILENAME"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("data.xsl")]
        public string XSL_FILENAME {
            get {
                return ((string)(this["XSL_FILENAME"]));
            }
            set {
                this["XSL_FILENAME"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("notifybox.html")]
        public string NOTIFY_FILENAME {
            get {
                return ((string)(this["NOTIFY_FILENAME"]));
            }
            set {
                this["NOTIFY_FILENAME"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("result.html")]
        public string RESULT_HTML_FILENAME {
            get {
                return ((string)(this["RESULT_HTML_FILENAME"]));
            }
            set {
                this["RESULT_HTML_FILENAME"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("result.xml")]
        public string RESULT_XML_FILENAME {
            get {
                return ((string)(this["RESULT_XML_FILENAME"]));
            }
            set {
                this["RESULT_XML_FILENAME"] = value;
            }
        }
    }
}
